#!/usr/bin/env python3
"""
audio2pcm.py - Convert audio files to raw mono/stereo PCM binaries or C headers
with automatic downmixing and optional attenuation.
"""

import argparse
import math
import shutil
import sys
from pathlib import Path

# Python 3.13+ compatibility check for pydub
try:
    from pydub import AudioSegment
    from pydub.exceptions import CouldntDecodeError
except ModuleNotFoundError as e:
    if "audioop" in str(e):
        print(
            "Error: Missing 'audioop' module (removed in Python 3.13+).\n"
            "Run: pip install audioop-lts",
            file=sys.stderr,
        )
        sys.exit(1)
    raise


def check_dependencies():
    if not (shutil.which("ffmpeg") or shutil.which("avconv")):
        print(
            "Error: 'ffmpeg' not found in system PATH. Install ffmpeg to decode audio.",
            file=sys.stderr,
        )
        sys.exit(1)


def export_c_header(pcm_bytes: bytes, output_path: Path, var_name: str, rate: int):
    hex_lines = []
    chunk_size = 12
    for i in range(0, len(pcm_bytes), chunk_size):
        chunk = pcm_bytes[i : i + chunk_size]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    content = f"""#pragma once
#include <stdint.h>
#include <stddef.h>

// Generated by audio2pcm.py
// Format: 16-bit Signed PCM, Mono, {rate} Hz
// Length: {len(pcm_bytes) // 2} samples ({len(pcm_bytes)} bytes)

const size_t {var_name}_len = {len(pcm_bytes)};
const uint8_t {var_name}_data[] = {{
{chr(10).join(hex_lines)}
}};
"""
    output_path.write_text(content)


def process_file(
    input_file: Path,
    output_dir: Path,
    sample_rate: int,
    sample_width: int,
    channels: int,
    gain_db: float,
    generate_header: bool,
):
    try:
        audio = AudioSegment.from_file(input_file)
    except CouldntDecodeError:
        print(f"[SKIP] Unsupported audio file: {input_file.name}", file=sys.stderr)
        return
    except Exception as e:
        print(f"[ERROR] Failed {input_file.name}: {e}", file=sys.stderr)
        return

    # Downmix channels (Mono = average of L + R)
    if audio.channels != channels:
        audio = audio.set_channels(channels)

    # Apply gain/attenuation only if non-zero
    if gain_db != 0.0:
        audio = audio.apply_gain(gain_db)

    # Resample & format depth
    normalized = audio.set_frame_rate(sample_rate).set_sample_width(sample_width)
    pcm_bytes = normalized.raw_data

    stem = input_file.stem
    mode_str = "mono" if channels == 1 else "stereo"
    output_bin = output_dir / f"{stem}_{sample_rate // 1000}k_{mode_str}.pcm"
    output_bin.write_bytes(pcm_bytes)

    gain_str = f"{gain_db:+.1f} dB" if gain_db != 0.0 else "unity gain (0.0 attenuation)"
    print(f"[OK] {input_file.name} -> {output_bin.name} ({len(pcm_bytes):,} bytes, {gain_str})")

    if generate_header:
        header_path = output_dir / f"{stem}_{sample_rate // 1000}k.h"
        clean_var = "".join(c if c.isalnum() else "_" for c in stem)
        export_c_header(pcm_bytes, header_path, clean_var, sample_rate)
        print(f"     Header: {header_path.name}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert audio assets into raw headerless PCM for embedded hardware."
    )
    parser.add_argument("source", type=Path, help="Audio file or folder")
    parser.add_argument("-o", "--output-dir", type=Path, default=None)
    parser.add_argument("-r", "--rate", type=int, default=16000, help="Hz (default: 16000)")
    parser.add_argument("-c", "--channels", type=int, default=1, choices=[1, 2], help="Default: 1 (Mono)")
    parser.add_argument("-w", "--width", type=int, default=2, choices=[1, 2, 4], help="Bytes/sample: 2 = 16-bit")
    parser.add_argument(
        "--attenuate",
        type=float,
        default=0.0,
        help="Attenuation amount. Default: 0.0 (no attenuation / full volume). "
             "Pass a fraction (e.g. 0.333 for 1/3 amplitude) or dB reduction (e.g. 6 for -6 dB).",
    )
    parser.add_argument(
        "--gain-db",
        type=float,
        default=None,
        help="Explicit gain in dB (overrides --attenuate, e.g. -6.0 or -9.54)",
    )
    parser.add_argument("--header", action="store_true", help="Generate C/C++ header array")

    args = parser.parse_args()
    check_dependencies()

    source = args.source
    if not source.exists():
        print(f"Error: Source path '{source}' not found.", file=sys.stderr)
        sys.exit(1)

    out_dir = args.output_dir or (source.parent if source.is_file() else source)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Calculate final dB offset
    if args.gain_db is not None:
        target_gain = args.gain_db
    elif args.attenuate <= 0.0:
        target_gain = 0.0  # 0.0 attenuation -> unity gain (no change)
    elif 0.0 < args.attenuate < 1.0:
        # Linear amplitude fraction (e.g., 0.333 -> ~ -9.55 dB)
        target_gain = 20.0 * math.log10(args.attenuate)
    else:
        # Values >= 1.0 treated as positive dB attenuation (e.g., 6.0 -> -6.0 dB)
        target_gain = -abs(args.attenuate)

    exts = {".mp3", ".wav", ".ogg", ".flac", ".m4a", ".aac"}
    if source.is_file():
        process_file(source, out_dir, args.rate, args.width, args.channels, target_gain, args.header)
    else:
        files = [f for f in source.iterdir() if f.suffix.lower() in exts]
        if not files:
            print(f"No audio files found in {source}.")
            return
        for f in sorted(files):
            process_file(f, out_dir, args.rate, args.width, args.channels, target_gain, args.header)


if __name__ == "__main__":
    main()