/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_STORAGE_FILES           1
#define MMAP_STORAGE_CHECKSUM        0x6B50

enum MMAP_STORAGE_LISTS {
    MMAP_STORAGE_SPACE_CAT_BIN = 0,        /*!< space_cat.bin */
};
